api_add_subscriber:
    pattern: /subscriber/add.json
    defaults: { _controller: "HermesHermesBundle:Api/Subscriber:add" }
    requirements:
        _method: [PUT, POST]

api_add_subscriber:
    pattern: /{_locale}/subscriber/add.json
    defaults: { _controller: "HermesHermesBundle:Api/Subscriber:add" }
    requirements:
        _method: [PUT, POST]
